### ISSUE TITLE
maybe a bug in input.go: "func EditDynamicWithCallback"?

### ISSUE THREAD

**Issue by Jiffies-Duke** [japanoise/termbox-util#1]
i am using your gomacs on windows. it is great. but there is something disturbing me: when i press c-x c-f to find a file in gomacs, there is an  extra space between the char i just entered and the cursor. 
i traced it back here, and found in this func "func EditDynamicWithCallback" line 203 around:
at the first time entering this func, buffer is empty "",  and 
`r, _ := utf8.DecodeLastRuneInString(buffer)`
returns "RuneError", Runewidth(r) is 2 (by output.go line 27).
so here it is: i entered one char, and cursor moved 2 spaces right.
sorry if i made some mistake. 
and sorry i am too lazy to make a pull request.

**Comment by japanoise** [comment]
My hunch (judging by a golang stdlib function failing where it really shouldn't, combined with the fact that it's windows and you have CJK in your repositories) is that maybe you're using a non-UTF-8 locale. What's the content of `buffer` when this function fails (as a list of bytes rather than a string)?

**Comment by Jiffies-Duke** [comment]
My PC box is running Windows 10, x64, Chinese.
The default locale under is gbk, not utf-8.

The extra space between the character and the cursor is there as soon as I input the first char, no matter what the buffer content is, even it is empty.

By the way, I have changed the termbox reference from nsf/termbox-go to gdamore/tcell/termbox for better CJK support. Maybe that is the cause of this extra space.

Anyway, I changed the code here. now gomacs works great. Thanks for your efforts on this convenient tool.

**Comment by japanoise** [comment]
>I have changed the termbox reference from nsf/termbox-go to gdamore/tcell/termbox for better CJK support

Noting this down as something to look into in future. I did notice that the tcell guys ported termbox to tcell, and I'd considered using it for gomacs since gomacs' sister editor micro uses it.

I'm aware there are issues with utf-8 when it comes to CJK, and that generally other encodings are preferred; it's a funny situation, since in the west (afaict) we almost exclusively use utf-8. Unfortunately I don't have time to mess with locales to properly support other encodings, but it's certainly a "nice-to-have". Future reference for myself [here](https://en.wikipedia.org/wiki/GBK_(character_encoding))

I'm glad you're enjoying gomacs, feel free to file any proposed improvements as tickets :)
